# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('discussion', 'Private discussion'), ('public_channel', 'Public Channel'), ('private_channel', 'Private Channel')], max_length=50),
        ),
    ]
