# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20170327_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='last_seen_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
    ]
