# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20170327_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('system', 'System message'), ('user', 'User message')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagetag',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='messaging.Message'),
        ),
    ]
