# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEND', 'Pending request'), ('RJCT', 'Friendship rejected'), ('ACPT', 'Friendship accepted')], max_length=10)),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('friendship_end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('addresser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_received_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_initiated_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
