# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(b'HUM', b'Human user'), (b'BOT', b'Bot')], default=b'HUM', max_length=4),
        ),
    ]
