# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20170413_0001'),
        ('core', '0002_user_type'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='user',
#            name='last_listening_date',
#            field=models.DateTimeField(null=True),
#        ),
#        migrations.AddField(
#            model_name='user',
#            name='listening_thread',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread'),
#        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name=b'profile_picture'),
        ),
    ]
