# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170416_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
